// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hmYwO3jU8UN6ZdPaicuO_ovfnT7DwU4',
    appId: '1:59279073337:web:223885ab6ade352cb62de8',
    messagingSenderId: '59279073337',
    projectId: 'agrismart-fb805',
    authDomain: 'agrismart-fb805.firebaseapp.com',
    storageBucket: 'agrismart-fb805.firebasestorage.app',
    measurementId: 'G-VQLMG2EM5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkhQOn7_C4MGeGLiDkdkqqsDVDHu9lXI',
    appId: '1:59279073337:android:f3c9c657bbf9643fb62de8',
    messagingSenderId: '59279073337',
    projectId: 'agrismart-fb805',
    storageBucket: 'agrismart-fb805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENU8IEApE0uj-dPi_NslWMZlKZ52CfGY',
    appId: '1:59279073337:ios:48dd31b8d8a62ba9b62de8',
    messagingSenderId: '59279073337',
    projectId: 'agrismart-fb805',
    storageBucket: 'agrismart-fb805.firebasestorage.app',
    iosBundleId: 'com.example.agrismartFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENU8IEApE0uj-dPi_NslWMZlKZ52CfGY',
    appId: '1:59279073337:ios:48dd31b8d8a62ba9b62de8',
    messagingSenderId: '59279073337',
    projectId: 'agrismart-fb805',
    storageBucket: 'agrismart-fb805.firebasestorage.app',
    iosBundleId: 'com.example.agrismartFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hmYwO3jU8UN6ZdPaicuO_ovfnT7DwU4',
    appId: '1:59279073337:web:e06120c9e00d053fb62de8',
    messagingSenderId: '59279073337',
    projectId: 'agrismart-fb805',
    authDomain: 'agrismart-fb805.firebaseapp.com',
    storageBucket: 'agrismart-fb805.firebasestorage.app',
    measurementId: 'G-9NFM19F00P',
  );
}
